# ansible/playbook.yml
---
- hosts: minecraft
  become: yes
  vars:
    jar_url: "https://piston-data.mojang.com/v1/objects/8dd1a28015f51b1803213892b50b7b4fc76e594d/server.jar"

  tasks:
    - name: Install Java and screen
      apt:
        name: ["openjdk-17-jdk", "screen"]
        state: present
        update_cache: yes

    - name: Create Minecraft user and directory
      block:
        - name: Create user
          user:
            name: minecraft
            home: /opt/minecraft
            shell: /bin/bash
            system: yes
        
        - name: Create server directory
          file:
            path: /opt/minecraft/server
            state: directory
            owner: minecraft
            group: minecraft
            mode: '0755'

    - name: Download server jar
      get_url:
        url: "{{ jar_url }}"
        dest: /opt/minecraft/server/server.jar
        owner: minecraft
        group: minecraft
        mode: '0644'

    - name: Create EULA file
      copy:
        dest: /opt/minecraft/server/eula.txt
        content: |
          #By changing the setting below to TRUE you are indicating your agreement to our EULA.
          eula=true
        owner: minecraft
        group: minecraft
        mode: '0644'

    - name: Start server temporarily to generate config
      command: >
        /usr/bin/sudo -u minecraft /usr/bin/screen -dmS minecraft
        /usr/bin/java -Xmx1G -Xms1G -jar server.jar nogui
      args:
        chdir: /opt/minecraft/server
      async: 120
      poll: 0

    - name: Wait for server to initialize
      pause:
        seconds: 30

    - name: Stop temporary server
      command: /usr/bin/sudo -u minecraft /usr/bin/screen -S minecraft -X quit
      ignore_errors: yes

    - name: Create systemd service
      copy:
        dest: /etc/systemd/system/minecraft.service
        content: |
          [Unit]
          Description=Minecraft Server
          After=network.target

          [Service]
          User=minecraft
          WorkingDirectory=/opt/minecraft/server
          ExecStart=/usr/bin/java -Xmx2G -Xms1G -jar server.jar nogui
          Restart=always
          SuccessExitStatus=143

          [Install]
          WantedBy=multi-user.target

    - name: Enable and start service
      systemd:
        name: minecraft
        enabled: yes
        state: started
        daemon_reload: yes
